version: '3'

services:
  
  db:
    image: mdillon/postgis
    environment:
      - ./environment/db.env
    expose:
      - "5432" # Allow other containers to call DB...
  
  wget_handler:
    image: dmw2151/wget-lambda
    expose:
      - "9000"
    volumes:
        - ~/.aws-lambda-rie:/aws-lambda
        - ./wget_handler/handler.py:/function/handler.py
    entrypoint: /aws-lambda/aws-lambda-rie
    command: "/usr/local/bin/python -m awslambdaric app.handler"
  
  pg_restore_handler:
    image: dmw2151/pg-restore-lambda
    expose:
      - "9000"
    volumes:
        - ~/.aws-lambda-rie:/aws-lambda
        - ./pg_restore_handler/handler.py:/function/handler.py
    entrypoint: /aws-lambda/aws-lambda-rie
    command: "/usr/local/bin/python -m awslambdaric app.handler"
              