version: '3'

services:
  
  wget_handler:
    image: dmw2151/wget-lambda
    ports: # Optional mapping to host for local testing
      - "9000:8080"
    volumes:
      - ./wget_handler/handler.py:/var/task/handler.py
    env_file:
      - ./test/environment/wget.env
    links:
      - s3
    command: handler.handler

  pg_restore_handler:
    image: dmw2151/pg-restore-lambda
    ports: # Optional mapping to host for local testing
      - "9001:8080"
    links:
      - s3
      - db
    volumes:
        - ./pg_restore_handler/handler.py:/var/task/handler.py
    env_file:
      - ./test/environment/restore.env
    command: handler.handler
  
  s3:
    image: lphoward/fake-s3
    volumes:
      - "./test/fake_s3/:/fakes3_root/"
    expose:
      - "4569"
    ports: # Optional mapping to host for local testing
      - "4569:4569"  
  
  db:
    image: mdillon/postgis
    env_file:
      - ./test/environment/db.env
    expose:
      - "5432" # Allow other containers to call DB...
  
  
              